apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zbx-env
  labels:
    app: {{ .Release.Name }}-zbx-env
    chart: {{ .Release.Name }}
data:
  MYSQL_DATABASE: {{ .Values.database.zabbix.database }}
  MYSQL_USER: {{ .Values.database.zabbix.user }}
  MYSQL_PASSWORD: {{ .Values.database.zabbix.password }}
  DB_SERVER_HOST: "{{ .Release.Name}}-db"
  DB_SERVER_PORT: "3306"
  ZBX_SERVER_NAME: "SPC-Zabbix"
  ZBX_SERVER_HOST: "{{ .Release.Name }}-server"
  ZBX_SERVER_PORT: "10051"
  ZBX_MEMORYLIMIT: "256M"
  ZBX_LOGSLOWQUERIES: "10000"
  ZBX_ALERTSCRIPTPATH: "/usr/lib/zabbix/alertscripts"
  ZBX_EXTERNALSCRIPTS: "/usr/lib/zabbix/externalscripts"
  ZBX_TIMEOUT: "30"
  ZBX_HOUSEKEEPINGFREQUENCY: "0"
  ZBX_MAXHOUSEKEEPERDELETE: "10000"
  ZBX_STARTPOLLERS: "50"
  ZBX_STARTPOLLERSUNREACHABLE: "5"
  ZBX_IPMIPOLLERS: "5"
  ZBX_STARTDBSYNCERS: "5"
  ZBX_STARTTIMERS: "5"
  ZBX_STARTESCALATORS: "5"
  ZBX_STARTALERTERS: "5"
  ZBX_CACHESIZE: "128M"
  ZBX_HISTORYCACHESIZE: "64M"
  ZBX_HISTORYINDEXCACHESIZE: "32M"
  ZBX_TRENDCACHESIZE: "32M"
  ZBX_VALUECACHESIZE: "64M"
  PHP_TZ: "Etc/UTC"
