{{- if .Values.mariadb.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-conf
  labels:
    app: {{ .Release.Name }}-db-conf
    chart: {{ .Release.Name }}
data:
  my.cnf: |-
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=utf8

    [mysqld]
    log-warnings=1
    default-storage-engine=InnoDB
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    tmpdir=/opt/bitnami/mariadb/tmp
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    bind-address=0.0.0.0

    ## Character set
    collation-server=utf8_unicode_ci
    init_connect='SET NAMES utf8'
    character-set-server=utf8

    ## MyISAM
    key_buffer_size=128M
    myisam_recover_options=FORCE,BACKUP

    ## safety
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    #transaction_isolation=REPEATABLE-READ
    skip-host-cache
    skip-name-resolve
    max_allowed_packet={{- required "max_allowed_packet is required!" .Values.mariadb.config.maxAllowedPacket }}
    sort_buffer_size=1M
    read_buffer_size=1M
    join_buffer_size=1M
    read_rnd_buffer_size=1M
    thread_stack=256K
    binlog_cache_size=256K
    max_connect_errors=1000000
    sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
    sysdate_is_now=1
    connect_timeout=30
    net_read_timeout={{- required "net_read_timeout is required!" .Values.mariadb.config.netReadTimeout }}
    net_write_timeout={{- required "net_write_timeout is required!" .Values.mariadb.config.netWriteTimeout }}
    wait_timeout={{- required "wait_timeout is required!" .Values.mariadb.config.waitTimeout }}
    #interactive_timeout=300
    innodb=FORCE

    # Mandatory per https://github.com/codership/documentation/issues/25
    innodb_autoinc_lock_mode=2
    # Per https://www.percona.com/blog/2006/08/04/innodb-double-write/
    innodb_doublewrite=0
    # Not fully ACID compliant, up to 1sec transaction loss in the event of total cluster failure (across both regions)
    # Enabled for performance per https://mariadb.com/kb/en/mariadb/getting-started-with-mariadb-galera-cluster/
    #innodb_flush_log_at_trx_commit=0

    ## binary logging
    log-bin=mysql-bin
    event_scheduler=ON
    expire_logs_days=1
    # Disabling for performance per http://severalnines.com/blog/9-tips-going-production-galera-cluster-mysql
    sync_binlog=0
    # Required for Galera
    binlog_format=row
    ## Caches and limits
    tmp_table_size=256M
    max_binlog_size=256M
    max_heap_table_size=256M
    # Re-enabling as now works with Maria 10.1.2
    query_cache_type=1
    query_cache_limit=1M
    query_cache_size=64M
    max_connections={{- required "max_connections required!" .Values.mariadb.config.maxConnections }}
    table_cache=256
    thread_cache_size=100
    open_files_limit=65535
    table_definition_cache=4096
    table_open_cache=4096
    ## innodb
    innodb_io_capacity=500
    innodb_flush_method=O_DIRECT
    innodb_log_files_in_group=2
    innodb_log_file_size=512M
    innodb_log_buffer_size=512M
    innodb_lock_wait_timeout=300
    innodb_flush_log_at_trx_commit=0    # Not ACID, but for performance. May loose data for 1 sec if crash happens
    innodb_file_per_table=1
    innodb_thread_concurrency=8
    innodb_write_io_threads=8
    innodb_read_io_threads=8
    innodb_data_file_path=ibdata1:256M:autoextend
    # 80% Memory is default reco.
    # Need to re-evaluate when DB size grows
    innodb_buffer_pool_size={{- required "innodb_buffer_pool_size is required!" .Values.mariadb.config.bufferPoolSize }}
    # MySQL 5.6/7 default
    innodb_buffer_pool_instances=8
    innodb_strict_mode=0

    ## logging
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    # Turn off for ProxySQL state monitoring quries
    log_queries_not_using_indexes=0
    slow_query_log=1

    [mariadb]
    plugin_load_add=auth_pam

{{- end -}}
