---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-table-partitioner
  labels:
    app: {{ .Release.Name }}-table-partitioner
    chart: {{ .Release.Name }}
spec:
  concurrencyPolicy: {{ .Values.cronjob.partitioner.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronjob.partitioner.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/bash
            - -c
            - mysql --user="root" --password="{{ .Values.database.root.password }}" --host="{{ .Release.Name }}-db"
              "$@" "zabbix" -e "call zabbix.drop_partitions('zabbix');call zabbix.create_next_partitions('zabbix');select * from zabbix.manage_partitions_history;"
            image: {{ template "partitioner.image" . }}
            name: pt-watcher
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: {{ .Values.cronjob.partitioner.schedule }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.partitioner.successfulJobsHistoryLimit }}
  suspend: false
