---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
    chart: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
        chart: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      initContainers:
      - name: check-resource
        image: {{ template "check.resource.image" .}}
        imagePullPolicy: {{ .Values.image.checkResource.pullPolicy | quote }}
        command:
          - python
        args:
          - /python/check-resources.py
        env:
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: RESOURCE
            value: job
          - name: DEPLOY_NAME
            value: {{ .Release.Name }}-restore
      containers:
      - name: zabbix-agent
        image: {{ template "zabbix.agent.image" . }}
        imagePullPolicy: {{ .Values.image.zabbixAgent.pullPolicy | quote }}
        ports:
        - containerPort: 10050
          name: zabbix-agent
        {{- if .Values.zabbix.agent.env }}
        env:
        {{- range .Values.zabbix.agent.env }}{{ $envname := .name }}
        - name: {{ .name }}
          value: "{{ required (printf "%s is required" $envname) .value }}"
        {{- end }}
        {{- end }}
      - name: zabbix-server
        image: {{ template "zabbix.server.image" . }}
        imagePullPolicy: {{ .Values.image.zabbixServer.pullPolicy | quote }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 162
          name: snmptrapd
        - containerPort: 10051
          name: zabbix-trapper
        - containerPort: 10052
          name: zabbix-jmx
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-zbx-env
        env:
        - name: ZBX_DEBUGLEVEL
          value: "{{ .Values.zabbix.server.debugLevel }}"
        {{- range .Values.zabbix.server.env }}{{ $envname := .name }}
        - name: {{ .name }}
          value: "{{ required (printf "%s is required" $envname) .value }}"
        {{- end }}
